# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         swished
version:      0.10
version_from: lib/SWISHED.pm
installdirs:  site
requires:
    SWISH::API:                    0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
